
export const metadata = {
  title: "Generate - Thinkr",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>   
        {children}
    </>
  );
}
